apiVersion: v1
kind: Service
metadata:
  name: compute-control
  labels: { app: compute-control }
spec:
  selector: { app: compute-control }
  ports:
    - { name: http, port: 8086, targetPort: 8086 }
