apiVersion: v1
kind: Service
metadata:
  name: matching-engine
  labels: { app: matching-engine }
spec:
  selector: { app: matching-engine }
  ports:
    - { name: http, port: 8087, targetPort: 8087 }
