apiVersion: v1
kind: Secret
metadata:
    name: platform-auth
    namespace: default
type: Opaque
stringData:
    PLATFORM_JWT_SECRET: ENC[AES256_GCM,data:7Emt5jBWaVD3CJRccBBZOAKMvnzJGI+NhnbHu/6u1EAYOceSNuXvpTpIXlvfl5Y8V4NAu8KPUPr5DBw0rD4dGg==,iv:UhS2CqxQOzU6HjgUS5qabdOEHWbSE2PEpzCjFkwhl74=,tag:584OpUIX8zNin4wChSyIxA==,type:str]
    SERVICE_TOKEN: ENC[AES256_GCM,data:2f1BpXmsoQTiXb5R3YcPEdG5sjmBmnI/VTif+9p1fijnLHuDhyobED8nlbH9Sp2oP4giOXUB+gZrAhHJwYd+VQ==,iv:NXF2QmPWDs1Zbma36QQ22CjGLT/s35bh/SM06EmyWgs=,tag:dAJauF3k+v8ejyN6Yh2Lmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hwhpzgfgvkk4fzlexfhmn9jnthfrhm3ek9gqera3xlzm7z2jagmq8dm4u5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcThpQVo0Q0krWVh5TUEx
            VjNQaXZPNlFOclB2QzZvc1R1U0dvRW9kK0hJCno0anNnZHV6SFpxYzlBeSs0TlRi
            ZzVPSjMxNENDcEJqcE4zWHREZkdtUWMKLS0tIGVVVStseXN2MHFEQTdDc1UyTXpr
            MTFURnlibngzVG9sVXNKZGd2TGV6NTgKL+0DPRG70s0tZ+9sCvfghgyJaQvRLG54
            HkM9Wj/SxXqeRsjvorUJ5PfQ+tyH5DNJsUQ6mZBYuXh4tbTi/IKtmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T15:33:19Z"
    mac: ENC[AES256_GCM,data:fZU3KAVRE79rzjf0cMV9GAjRufrh55H5IdaT+V6iudImgF6c1P8tlKDBczkqNieJZKXRYxA2J8Mh5Q4Z+7fJpVE1x0L5JXZBSD/oo7CFAZNicO0ogzcDqJa3DNnNrv1Wpo0LvK5XDkJHIBUOaoz3IaFt0I6xdfcfiwdgBMrXY28=,iv:1ya8AagQnO2du1eM23EzJlO2astajF/MhPbfBxFAkhE=,tag:tnUs8PfRKUvqjZr1AAcA3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
